import Script from "next/script";
import "./globals.css";

export const metadata = {
    title: "IGNITE 2026!",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={` antialiased`}>
                <Script src="https://www.googletagmanager.com/gtag/js?id=G-CX4WJMZ8ZQ" />
                    <Script id="google-analytics" strategy="afterInteractive">
                    {`
                        window.dataLayer = window.dataLayer || [];
                        function gtag(){dataLayer.push(arguments);}
                        gtag('js', new Date());
                        gtag('config', 'G-CX4WJMZ8ZQ');
                    `}
                    </Script>
                {children}
                <Script
                    src="https://players.brightcove.net/3745659807001/hXGs3fyvO_default/index.min.js"
                    strategy="afterInteractive"
                />
            </body>
        </html>
    );
}
