import Script from "next/script";
import "./globals.css";

export const metadata = {
    title: "MLST Live Stream",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={` antialiased`}>
                <Script async src="https://www.googletagmanager.com/gtag/js?id=G-034XRGX66F"></Script>
                <Script
                    id="google-tag-manager"
                    strategy="beforeInteractive"
                >{`window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-034XRGX66F');`}</Script>
                {children}
                <Script
                    src="https://players.brightcove.net/3745659807001/hXGs3fyvO_default/index.min.js"
                    strategy="afterInteractive"
                />
            </body>
        </html>
    );
}
